import { Reporter } from "@playwright/test/reporter";
import fs from "fs";
import path from "path";

export default class MetadataReporter implements Reporter {
  async onExit() {
    // Locate the index.html generated by the Playwright HTML reporter
    const reportPath = path.resolve(
      process.cwd(),
      "playwright-report",
      "index.html",
    );

    if (fs.existsSync(reportPath)) {
      let html = fs.readFileSync(reportPath, "utf8");

      const studentId = process.env.STUDENT_ID || "UNKNOWN_STUDENT_ID";
      const studentName = process.env.STUDENT_NAME || "Unknown Name";

      const injection = `
        <style>
          #root {
            margin-top: 180px !important;
          }

          .report-title-wrapper {
            position: absolute;
            top: 0;
            left: 0;
            width: calc(100%);
            z-index: 999999;
          }

          .report-title {
            width: calc(100% - 48px);
            margin: 20px auto 0;
            padding: 20px 28px;

            background: linear-gradient(135deg, #33547c, #1e4178);
            border-radius: 12px;
            color: white;

            box-shadow:
              0 6px 18px rgba(59,130,246,.25),
              0 2px 6px rgba(0,0,0,.08);

            font-family:
              Inter,
              system-ui,
              -apple-system,
              BlinkMacSystemFont,
              "Segoe UI",
              sans-serif;
            box-sizing: border-box;
          }

          .report-title h1 {
            margin: 0;
            text-align: center;
            font-size: 30px;
            font-weight: 700;
            letter-spacing: .4px;
          }

          .report-title .subtitle {
            margin-top: 6px;
            text-align: center;
            font-size: 15px;
            opacity: .9;
          }

          .report-info {
            margin-top: 18px;
            padding-top: 16px;

            border-top: 1px solid rgba(255,255,255,.25);

            display: flex;
            justify-content: center;
            gap: 32px;
            flex-wrap: wrap;

            font-size: 15px;
          }

          .report-info-item {
            display: flex;
            gap: 8px;
            align-items: center;
          }

          .report-info-item strong {
            font-weight: 600;
          }
        </style>

        <div class="report-title-wrapper">
          <div class="report-title">
            <h1>EShop Web Automation Testing</h1>
            <div class="subtitle">Playwright HTML Report</div>
            <div class="report-info">
              <div class="report-info-item">
                <strong>Author:</strong>
                <span>${studentName}</span>
              </div>
              <div class="report-info-item">
                <strong>Student ID:</strong>
                <span>${studentId}</span>
              </div>
              <div class="report-info-item">
                <strong>Email:</strong>
                <span>${studentId}@student.hcmus.edu.vn</span>
              </div>
              <div class="report-info-item">
                <strong>Date:</strong>
                <span>${new Date().toLocaleString("vi-VN")}</span>
              </div>
            </div>
          </div>
        </div>
      `;

      // Inject just before the closing body tag
      if (!html.includes("Author:")) {
        html = html.replace("</body>", `${injection}\n</body>`);
        fs.writeFileSync(reportPath, html, "utf8");
        console.log(
          "[MetadataReporter] Successfully injected metadata into the HTML report!",
        );
      }
    } else {
      console.warn(
        `[MetadataReporter] HTML report not found at ${reportPath}!`,
      );
    }
  }
}
